export enum AnimalSpecies {
  Dog = 'Dog',
  Cat = 'Cat',
  Rabbit = 'Rabbit',
  GuineaPig = 'GuineaPig',
  Hamster = 'Hamster',
  Ferret = 'Ferret',
  Rat = 'Rat',
  Mouse = 'Mouse',
  Bird = 'Bird',
  Reptile = 'Reptile',
  Amphibian = 'Amphibian',
  Fish = 'Fish',
  Horse = 'Horse',
  Cattle = 'Cattle',
  Pig = 'Pig',
  Sheep = 'Sheep',
  Goat = 'Goat',
  Exotic = 'Exotic'
}